MAIN_WIDGET_COLOR = "grey"
BOARD_WIDGET_COLOR = "white"
GRID_LEN = 20
NUM_GRID_PER_BOARD_ROW = 10
BOARD_LEN = GRID_LEN * NUM_GRID_PER_BOARD_ROW
MY_PIXEL_COLOR = "blue"
OTHER_PIXEL_COLOR = "pink"
OWN_N = 2
SERVER_HOST = "128.237.165.164" # "localhost" "128.237.202.200" 
#SERVER_HOST = "localhost"# "128.237.202.200" 
SERVER_PORT = 9999
MAX_GROUP_MEMBER_NUM = 3

FORM_GRID_LEN = 15 
NUM_GRID_PER_FORM_ROW = 5
FORM_LEN = FORM_GRID_LEN * NUM_GRID_PER_FORM_ROW
FORM_PIXEL_COLOR = "green"
FORM_WIDGET_COLOR = "white"

ONE_ROUND_SCORE = 10

def checkRange(x):
	if (x >= 0 and x < NUM_GRID_PER_BOARD_ROW):
		return True
	else:
		return False
